/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import BussinessLayer.CSDL;
import BussinessLayer.HangHoaBL;
import BussinessLayer.KhachhangBL;
import DataTransferObject.HangHoa;
import DataTransferObject.Khachhang;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author this pc
 */
public class frm_khachHang extends javax.swing.JFrame {

    /**
     * Creates new form av
     */
    private static DefaultTableModel TableModel = new DefaultTableModel();
    DefaultTableModel model;
    String maKH;

    public frm_khachHang() {
        initComponents();
        initkhachhang();
    }

    void initkhachhang() {
        List<Khachhang> listKH;
        listKH = KhachhangBL.dsKhachhang();
        if (listKH.size() > 0) {
            model = (DefaultTableModel) tbl_thongtinkh.getModel();
            for (Khachhang s : listKH) {
                model.addRow(new Object[]{s.getStrMakh(), s.getStrTenkh(), s.getStrGioitinh(), s.getStrDiachi(), s.getStrSdt()});
            }
        }
    }

    public static void LoadKH() {
        try (Connection ketNoi = CSDL.Connect()) {
            String sql = "SELECT * FROM KHACHHANG";
            PreparedStatement pst = ketNoi.prepareStatement(sql);
            ResultSet res = pst.executeQuery(sql);
            String[] colsName = {"MaKH", "TenKH", "Gioitinh", "Diachi", "SDT"};
            TableModel.setColumnIdentifiers(colsName);
            while (res.next()) {
                String rows[] = new String[10];
                rows[0] = res.getString(1);
                rows[0] = res.getString(2);
                rows[0] = res.getString(3);
                rows[0] = res.getString(4);
                rows[0] = res.getString(5);
                TableModel.addRow(rows);
            }
        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }

    public void macDinhKH() {
        txt_makh.setText(null);
        txt_tenkh.setText(null);
        cbo_gtkh.setSelectedIndex(0);
        txt_diachikh.setText(null);
        txt_sodtkh.setText(null);
    }

    public void Search(String str) {
        model = (DefaultTableModel) tbl_thongtinkh.getModel();
        TableRowSorter<DefaultTableModel> trs = new TableRowSorter<>(model);
        tbl_thongtinkh.setRowSorter(trs);
        trs.setRowFilter(RowFilter.regexFilter(str));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_thongtinkh = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txt_timkiemkh = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        btn_timkiemkh = new javax.swing.JButton();
        txt_makh = new javax.swing.JTextField();
        txt_tenkh = new javax.swing.JTextField();
        txt_diachikh = new javax.swing.JTextField();
        cbo_gtkh = new javax.swing.JComboBox<>();
        txt_sodtkh = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btn_themmoi = new javax.swing.JButton();
        btn_luu = new javax.swing.JButton();
        btn_xoa = new javax.swing.JButton();
        btn_sua = new javax.swing.JButton();
        btn_dangXuat = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 243, 243));

        jLabel2.setForeground(new java.awt.Color(39, 34, 87));
        jLabel2.setText("Tên khách hàng");

        tbl_thongtinkh.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã khách hàng", "Tên khách hàng", "Giới tính", "Địa chỉ", "Số điện thoại"
            }
        ));
        tbl_thongtinkh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_thongtinkhMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbl_thongtinkh);

        jLabel3.setForeground(new java.awt.Color(39, 34, 87));
        jLabel3.setText("Giới tính:");

        jLabel6.setForeground(new java.awt.Color(39, 34, 87));
        jLabel6.setText("Tìm kiếm khách hàng:");

        jLabel4.setForeground(new java.awt.Color(39, 34, 87));
        jLabel4.setText("Địa chỉ:");

        jLabel5.setForeground(new java.awt.Color(39, 34, 87));
        jLabel5.setText("Số điện thoại:");

        btn_timkiemkh.setForeground(new java.awt.Color(39, 34, 87));
        btn_timkiemkh.setText("Tìm kiếm");
        btn_timkiemkh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_timkiemkhActionPerformed(evt);
            }
        });

        cbo_gtkh.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Chọn giới tính", "Nam", "Nữ", "Khác" }));

        jLabel1.setForeground(new java.awt.Color(39, 34, 87));
        jLabel1.setText("Mã khách hàng:");

        btn_themmoi.setForeground(new java.awt.Color(39, 34, 87));
        btn_themmoi.setText("Thêm mới");
        btn_themmoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_themmoiActionPerformed(evt);
            }
        });

        btn_luu.setForeground(new java.awt.Color(39, 34, 87));
        btn_luu.setText("Lưu");
        btn_luu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_luuActionPerformed(evt);
            }
        });

        btn_xoa.setForeground(new java.awt.Color(39, 34, 87));
        btn_xoa.setText("Xóa");
        btn_xoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_xoaActionPerformed(evt);
            }
        });

        btn_sua.setForeground(new java.awt.Color(39, 34, 87));
        btn_sua.setText("Sửa");
        btn_sua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_suaActionPerformed(evt);
            }
        });

        btn_dangXuat.setForeground(new java.awt.Color(39, 34, 87));
        btn_dangXuat.setText("Đăng xuất");
        btn_dangXuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_dangXuatActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(39, 34, 87));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("THÔNG TIN KHÁCH HÀNG");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txt_tenkh, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(173, 173, 173)
                                .addComponent(txt_diachikh, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(58, 58, 58)
                                        .addComponent(cbo_gtkh, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(18, 18, 18)
                                        .addComponent(txt_makh, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(81, 81, 81)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel5)))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(173, 173, 173)
                                        .addComponent(txt_sodtkh, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 863, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(289, 289, 289)
                        .addComponent(jLabel7))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(207, 207, 207)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_timkiemkh, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btn_timkiemkh))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(btn_themmoi)
                        .addGap(127, 127, 127)
                        .addComponent(btn_luu, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addComponent(btn_dangXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btn_sua, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(120, 120, 120)
                                .addComponent(btn_xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(24, 24, 24)))))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7)
                .addGap(43, 43, 43)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_timkiemkh, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_timkiemkh, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt_tenkh, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_diachikh, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txt_makh, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txt_sodtkh, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbo_gtkh, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_themmoi, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_luu, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_sua, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_xoa, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btn_dangXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_themmoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_themmoiActionPerformed
        // TODO add your handling code here:
        macDinhKH();
    }//GEN-LAST:event_btn_themmoiActionPerformed

    private void btn_xoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_xoaActionPerformed
        // TODO add your handling code here:
        if (tbl_thongtinkh.getSelectedRow() < 0) {
            JOptionPane.showMessageDialog(rootPane, "Chọn thông tin cần xóa");
        } else {
            DefaultTableModel defaultTableModel = (DefaultTableModel) tbl_thongtinkh.getModel();
            int as = JOptionPane.showConfirmDialog(rootPane, "Bạn có muốn xóa khách hàng?", "Xác nhận xóa", JOptionPane.YES_NO_OPTION);
            if (as == JOptionPane.YES_OPTION) {
                KhachhangBL.xoaKH(String.valueOf(maKH));
            }
            defaultTableModel.setRowCount(0);
            macDinhKH();
            initkhachhang();
        }
    }//GEN-LAST:event_btn_xoaActionPerformed

    private void btn_luuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_luuActionPerformed
        // TODO add your handling code here:
        String maKH = txt_makh.getText();
        String tenKH = txt_tenkh.getText();
        String gioiTinh = cbo_gtkh.getSelectedItem().toString();
        String Diachi = txt_diachikh.getText();
        String sdt = txt_sodtkh.getText();
        KhachhangBL.themkhachhang(maKH, tenKH, gioiTinh, Diachi, sdt);
        JOptionPane.showMessageDialog(rootPane, "Thêm khách hàng thành công");
        model = (DefaultTableModel) tbl_thongtinkh.getModel();
        model.setNumRows(0);
        initkhachhang();
        macDinhKH();
    }//GEN-LAST:event_btn_luuActionPerformed

    private void btn_suaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_suaActionPerformed
        // TODO add your handling code here:
        String maKH = txt_makh.getText();
        String tenKH = txt_tenkh.getText();
        String gioiTinh = cbo_gtkh.getSelectedItem().toString();
        String Diachi = txt_diachikh.getText();
        String sdt = txt_sodtkh.getText();
        KhachhangBL.capNhatKH(maKH, tenKH, gioiTinh, Diachi, sdt);
        JOptionPane.showMessageDialog(rootPane, "Cập nhật thành công");
        model = (DefaultTableModel) tbl_thongtinkh.getModel();
        model.setNumRows(0);
        initkhachhang();
        LoadKH();
        macDinhKH();
    }//GEN-LAST:event_btn_suaActionPerformed

    private void btn_timkiemkhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_timkiemkhActionPerformed
        // TODO add your handling code here:
        List<Khachhang> listKH;
        maKH = txt_timkiemkh.getText();
        listKH = KhachhangBL.timkiemKH();
        if (listKH.size() <= 0) {
            JOptionPane.showMessageDialog(rootPane, "Không tìm thấy khách hàng cần tìm");
        } else {
            Search(maKH);
        }
    }//GEN-LAST:event_btn_timkiemkhActionPerformed

    private void tbl_thongtinkhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_thongtinkhMouseClicked
        // TODO add your handling code here:
        txt_makh.setText(String.valueOf(model.getValueAt(tbl_thongtinkh.getSelectedRow(), 0)));
        txt_tenkh.setText(String.valueOf(model.getValueAt(tbl_thongtinkh.getSelectedRow(), 1)));
        cbo_gtkh.setSelectedItem(String.valueOf(model.getValueAt(tbl_thongtinkh.getSelectedRow(), 2)));
        txt_diachikh.setText(String.valueOf(model.getValueAt(tbl_thongtinkh.getSelectedRow(), 3)));
        txt_sodtkh.setText(String.valueOf(model.getValueAt(tbl_thongtinkh.getSelectedRow(), 4)));

    }//GEN-LAST:event_tbl_thongtinkhMouseClicked

    private void btn_dangXuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_dangXuatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btn_dangXuatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_khachHang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_dangXuat;
    private javax.swing.JButton btn_luu;
    private javax.swing.JButton btn_sua;
    private javax.swing.JButton btn_themmoi;
    private javax.swing.JButton btn_timkiemkh;
    private javax.swing.JButton btn_xoa;
    private javax.swing.JComboBox<String> cbo_gtkh;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_thongtinkh;
    private javax.swing.JTextField txt_diachikh;
    private javax.swing.JTextField txt_makh;
    private javax.swing.JTextField txt_sodtkh;
    private javax.swing.JTextField txt_tenkh;
    private javax.swing.JTextField txt_timkiemkh;
    // End of variables declaration//GEN-END:variables
}
